version: '2'
services:

  nginx:
    extends:
      file: common-services.yml
      service: nginx-base
    volumes_from:
      - gunicorn
    depends_on:
      - gunicorn

  gunicorn:
    extends:
      file: common-services.yml
      service: gunicorn-base
    depends_on:
      - redis
      - postgres
      - rabbitmq
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: 'stream_anywhere.settings.production'

  redis:
    extends:
      file: common-services.yml
      service: redis-base

  postgres:
    extends:
      file: common-services.yml
      service: postgres-base
    env_file:
      - .env

  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq-base

  flower:
    extends:
      file: common-services.yml
      service: gunicorn-base
    entrypoint:
      - celery
      - flower
      - --app=stream_anywhere
    depends_on:
      - redis
      - postgres
      - rabbitmq
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: 'stream_anywhere.settings.production'

  celeryworker:
    extends:
      file: common-services.yml
      service: gunicorn-base
    entrypoint:
      - celery
      - -A
      - stream_anywhere
      - worker
      - -l
      - INFO
    depends_on:
      - redis
      - postgres
      - rabbitmq
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: 'stream_anywhere.settings.production'

  celerybeat:
    extends:
      file: common-services.yml
      service: gunicorn-base
    entrypoint:
      - celery
      - -A
      - stream_anywhere
      - beat
      - -l
      - INFO
    depends_on:
      - redis
      - postgres
      - rabbitmq
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: 'stream_anywhere.settings.production'
